export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CREATE_PARCEL_SUCCESS = 'CREATE_PARCEL_SUCCESS';
export const CREATE_PARCEL_FAIL = 'CREATE_PARCEL_FAIL';
export const GET_PARCEL_SUCCESS = 'GET_PARCEL_SUCCESS';
export const GET_PARCEL_ERROR = 'GET_PARCEL_ERROR';
export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_PARCELS_ERROR = 'GET_PARCELS_ERROR';
export const UPDATE_PARCEL_SUCCESS = 'UPDATE_PARCEL_SUCCESS';
export const UPDATE_PARCEL_ERROR = 'UPDATE_PARCEL_ERROR'




